name: Update Horizons Data

on:
  schedule:
    - cron: '15 2 * * *' # daily at 02:15 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Generate data
        run: npm run generate

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/data/positions.json
          git diff --cached --quiet || git commit -m "chore(data): update positions.json"
          git push
